on:
  push:
 
jobs:
  shellcheck:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:jammy
    steps:
      - uses: actions/checkout@v4
      - run: apt update
      - run: apt install -y shellcheck
      - run: shellcheck source=/etc/os-release environment_builder.sh
