on:
  push:
 
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - image: almalinux
          #   tag: 8.9-20231124
          # - image: almalinux
          #   tag: 9.3-20231124
          # - image: rockylinux
          #   tag: '8.9.20231119'
          # - image: rockylinux
          #   tag: '9.3.20231119'
          # - image: ubuntu
          #   tag: focal
          - image: ubuntu
            tag: jammy
    container:
      image: ${{ matrix.image }}:${{ matrix.tag }}
    steps:
      - run: cat /etc/os-release
      - run: apt update -y
      - run: apt upgrade -y
      - run: apt install python3.11
      - run: python3 -m venv $HOME/venv
      - run: source venv/bin/activate && pip install ansible
