on:
  push:
 
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - image: almalinux
            tag: 8.9-20231124
          - image: almalinux
            tag: 9.3-20231124
          - image: ubuntu
            tag: focal
          - image: ubuntu
            tag: jammy
    container:
      image: ${{ matrix.image }}:${{ matrix.tag }}
    steps:
      - run: lsb_release -a -u
