on:
  push:
 
jobs:
  example_matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - image: almalinux
          #   tag: 8.9-20231124
          # - image: almalinux
          #   tag: 9.3-20231124
          # - image: rockylinux
          #   tag: '8.9.20231119'
          # - image: rockylinux
          #   tag: '9.3.20231119'
          # - image: ubuntu
          #   tag: focal
          - image: ubuntu
            tag: jammy
    container:
      image: ${{ matrix.image }}:${{ matrix.tag }}
    steps:
      - uses: actions/checkout@v4
      - run: sh environment_builder.sh
